# Generated by Django 6.0.7 on 2026-07-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_author_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='blog_author',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='blog_comment',
        ),
        migrations.AlterModelTable(
            name='post',
            table='blog_post',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='blog_tag',
        ),
    ]
